### ISSUE TITLE
not working on Mac

### ISSUE THREAD

**Issue by trypythy** [stratisproject/stratisX#18]
Hi -- I had used this on my PC and it all went well but when I try using it on my mac, it just doesn't open. downloaded the .dmg, installed but when I try opening it, it just freezes for a few seconds and ends up with a dialogue - ignore, report, reopen.

**Comment by dev0tion** [comment]
Hey @trypythy,

Yes I know the error. It's a very generic error so it's hard to debug, it's not OS related because on other peoples Mac it works.
What you can do for now is use version 2.0.0.1: https://github.com/stratisproject/stratisX/releases/tag/v2.0.0.1

The interim wallet will be replaced by the C# wallet soon :).
