### ISSUE TITLE
Wallet not receiving funds It says Out of Sync?

### ISSUE THREAD

**Issue by mentortoli** [stratisproject/stratisX#31]
I made a transaction using chanelly.com over there at chanelly it says all done here the wallet haven't recieved nothing since it's out of sync.

**Comment by dev0tion** [comment]
Hi @mentortoli 

Please follow the steps described here to get back in sync:
https://github.com/stratisproject/stratisX/releases/tag/v2.0.0.3

Please let me know if that fixed it for you!

Grts

**Comment by mentortoli** [comment]
Now it started to sync it seems my norton antivirus was blocking the connection to stratis platform.

**Comment by dev0tion** [comment]
Hey @mentortoli,

Were you able to follow the steps above?
Norton normally shouldn't be blocking the connections, but we had a few problems with v2.0.0.2 of our client, that's why we release v2.0.0.3 that solves the issues people were having while syncing.

Please let me know if you're up and running again!

Grts

**Comment by mentortoli** [comment]
Actually yeah the norton was blocking the connection I turned it off for 15 min until syncing started and now it's syncing.

**Comment by dev0tion** [comment]
Ok mate. Let me know when it's done syncing and all is wel.

**Comment by mentortoli** [comment]
Sure I will let you know thanks

**Comment by mentortoli** [comment]
Syncing is all done and I also recieved the funds. Thanks

**Comment by dev0tion** [comment]
Good!
