### ISSUE TITLE
Shows 0 active connections for v 2.0.0.5 and hence unable to sync or send stratis

### ISSUE THREAD

**Issue by pdhimate** [stratisproject/stratisX#66]
I was on v2.0.0.3 when I had wallet backup file back in in 2017. Today, I installed StratQT/X v2.0.0.5 to move my STRATs to the latest Breeze wallet (v1.0.1). But turns out that I am unable to transact from the StratQT/X wallet v 2.0.0.5.

It seems to not fetch active connections and remains out of sync. Is there a way for me to send my STRATs without the sync? I did try using the CORE wallet but it seems that I can't have my older wallets backups imported there.

Opened up a discussion here as well: https://www.reddit.com/r/stratisplatform/comments/c9kr39/sending_stratis_from_qt_wallet_v_2003_to_breeze/

**Comment by pdhimate** [comment]
Found a work around check the reddit thread for solution.

**Comment by scorpy2k** [comment]
deleting appdata folder doesnt help.
still no sync.
any ideas? anyone?

**Comment by dev0tion** [comment]
Hi @scorpy2k, first of all make sure you're on v2.0.0.5.
Then add nodes into your stratis.conf file located in %appdata%/Stratis.
You can find a list of nodes at the "node list" button here: https://chainz.cryptoid.info/strat/#!network
Use the node list behind version /Stratis:2.0.0.5/

If you're still having issues, I recommend you to ping me on Discord in the #support channel.
https://discord.com/invite/9tDyfZs

**Comment by scorpy2k** [comment]
Hello, and thx so much for adwise. couldnt find that stratis.conf file, and made it by myself with node list inside. am i done wrong, or that should work?

now wallet got 6 active connections and 4years and 5 weeks behind...

**Comment by dev0tion** [comment]
That's great, now it should work. You just have to let it sync.
Please close the issue if all went well.

**Comment by scorpy2k** [comment]
all done, thanks a lot. you saved my money =)
how can i close that issue?

**Comment by dev0tion** [comment]
Nevermind, the issue is closed. You're welcome!

**Comment by User17871** [comment]
> That's great, now it should work. You just have to let it sync. Please close the issue if all went well.

Hello dev0tion, 

Hope you can help me out as well. 
I was just trying to restore an old wallet, which seems to work, when I import that wallet in Stratis v2.0.0.5 I see my balance (but unconfirmed).

Unfortunately the wallet is not syncing. 
I have added nodes to stratis.conf manually located in %appdata%/Stratis. 

I have just copy/pasted the whole list of nodes and made a stratis.conf file (saved as ALL FILES, not as txt). 
I copied nodes from https://chainz.cryptoid.info/strax/#!network

...I see now while typing that you refer to https://chainz.cryptoid.info/STRAT/#!network instead of STRAX. 

I am wondering if I am a bit late to this party maybe? 

Anyways, any toughts/help would be much appreciated. 

Thanks in advance. 

Kind regards,

JJ
